**Part 1**

- Loading California housing dataset, summarising, transforming, filtering and then exporting the data.

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('california_housing_train.csv')

In [3]:
df.head(5)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0

In [4]:
df.tail(10)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
16990    -124.22     41.73                28.0       3003.0           699.0   
16991    -124.23     41.75                11.0       3159.0           616.0   
16992    -124.23     40.81                52.0       1112.0           209.0   
16993    -124.23     40.54                52.0       2694.0           453.0   
16994    -124.25     40.28                32.0       1430.0           419.0   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
16990      1530.0       653.0         1.7038             78300.0  
16991      1343.0       479.0         2.4805             73200.0  
16992       544.0       172.0         3.3462             50800.0  
16993      1152.0       435.0         3.0806            106700.0  
16994       434.0       187.0         1.9417             76100.0  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0

In [5]:
df.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000   
mean    -119.562108     35.625225           28.589353   2643.664412   
std        2.005166      2.137340           12.586937   2179.947071   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.790000     33.930000           18.000000   1462.000000   
50%     -118.490000     34.250000           29.000000   2127.000000   
75%     -118.000000     37.720000           37.000000   3151.250000   
max     -114.310000     41.950000           52.000000  37937.000000   

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000   
mean       539.410824   1429.573941    501.221941       3.883578   
std        421.499452   1147.852959    384.520841       1.908157   
min          1.000000      3.000000      1.000000       0.499900   
25%        297.000000    790.000000    282.000000       2.566375   
50%        434.000000   1167.000000    409.000000       3.544600   
75%        648.250000   1721.000000    605.250000       4.767000   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        17000.000000  
mean        207300.912353  
std         115983.764387  
min          14999.000000  
25%         119400.000000  
50%         180400.000000  
75%         265000.000000  
max         500001.000000

In [7]:
vals = set(df["total_bedrooms"])
print(len(vals))

1848


In [8]:
df["total_bedrooms_per_total_rooms"] = (df["total_bedrooms"]/df["total_rooms"])/2

In [9]:
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  \
0          1015.0       472.0         1.4936             66900.0   
1          1129.0       463.0         1.8200             80100.0   
2           333.0       117.0         1.6509             85700.0   
3           515.0       226.0         3.1917             73400.0   
4           624.0       262.0         1.9250             65500.0   
...           ...         ...            ...                 ...   
16995       907.0       369.0         2.3571            111400.0   
16996      1194.0       465.0         2.5179             79000.0   
16997      1244.0       456.0         3.0313            103600.0   
16998      1298.0       478.0         1.9797             85800.0   
16999       806.0       270.0         3.0147             94600.0   

       total_bedrooms_per_total_rooms  
0                            0.114309  
1                            0.124248  
2                            0.120833  
3                            0.112258  
4                            0.112105  
...                               ...  
16995                        0.088859  
16996                        0.112388  
16997                        0.099178  
16998                        0.103293  
16999                        0.082418  

[17000 rows x 10 columns]

In [10]:
mean = df["total_bedrooms_per_total_rooms"].mean()
sd = df["total_bedrooms_per_total_rooms"].std()
print(mean)
print(sd)

0.10637999410517401
0.028911504451580836


In [12]:
df[df["median_income"]>5]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
32       -115.39     32.76                16.0       1136.0           196.0   
69       -115.55     32.98                33.0       2266.0           365.0   
92       -115.57     32.78                20.0       1534.0           235.0   
98       -115.58     32.78                 5.0       2494.0           414.0   
100      -115.59     32.79                 8.0       2183.0           307.0   
...          ...       ...                 ...          ...             ...   
16737    -122.89     38.38                16.0       2017.0           369.0   
16762    -122.94     38.57                33.0       1530.0           266.0   
16776    -123.00     38.33                 8.0       3223.0           637.0   
16802    -123.17     39.18                14.0       2240.0           327.0   
16899    -124.05     40.94                14.0       1452.0           217.0   

       population  households  median_income  median_house_value  \
32          481.0       185.0         6.2558            146300.0   
69          952.0       360.0         5.4349            143000.0   
92          871.0       222.0         6.2715             97200.0   
98         1416.0       421.0         5.7843            110100.0   
100        1000.0       287.0         6.3814            159900.0   
...           ...         ...            ...                 ...   
16737       931.0       336.0         5.7664            267500.0   
16762       728.0       250.0         5.1005            266700.0   
16776       851.0       418.0         5.6445            364800.0   
16802      1030.0       308.0         5.9585            214900.0   
16899       516.0       181.0         5.0329            165600.0   

       total_bedrooms_per_total_rooms  
32                           0.086268  
69                           0.080538  
92                           0.076597  
98                           0.082999  
100                          0.070316  
...                               ...  
16737                        0.091472  
16762                        0.086928  
16776                        0.098821  
16802                        0.072991  
16899                        0.074725  

[3752 rows x 10 columns]

In [13]:
newdf = df[(df["total_rooms"]>10000) & (df["median_house_value"] <150000)]

In [14]:
newdf

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
133      -116.06     34.15                15.0      10377.0          2331.0   
191      -116.36     33.88                11.0      12557.0          3098.0   
198      -116.38     33.73                10.0      11836.0          2405.0   
201      -116.39     33.82                15.0      11115.0          2257.0   
229      -116.47     33.81                 7.0      10105.0          2481.0   
...          ...       ...                 ...          ...             ...   
12654    -121.75     38.67                 9.0      12139.0          2640.0   
12772    -121.79     36.64                11.0      32627.0          6445.0   
13388    -121.94     38.27                35.0      10869.0          2226.0   
13707    -122.00     38.25                 7.0      11768.0          1893.0   
15436    -122.31     40.55                11.0      13714.0          2302.0   

       population  households  median_income  median_house_value  \
133        4507.0      1807.0         2.2466             66800.0   
191        2453.0      1232.0         1.7844             78500.0   
198        3811.0      1570.0         4.0079            134500.0   
201        4122.0      1653.0         2.7219             74400.0   
229        6274.0      2095.0         2.4497             90900.0   
...           ...         ...            ...                 ...   
12654      6837.0      2358.0         3.1250            132500.0   
12772     28566.0      6082.0         2.3087            118800.0   
13388      9879.0      2152.0         2.5681             81300.0   
13707      6657.0      1874.0         4.9222            142900.0   
15436      6511.0      2267.0         3.5522            100100.0   

       total_bedrooms_per_total_rooms  
133                          0.112316  
191                          0.123357  
198                          0.101597  
201                          0.101529  
229                          0.122761  
...                               ...  
12654                        0.108740  
12772                        0.098768  
13388                        0.102401  
13707                        0.080430  
15436                        0.083929  

[67 rows x 10 columns]

**Part 2**

- Exploring NumPy

In [15]:
a = np.array(range(1,21))

In [16]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [21]:
even = a[1::2]
even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [24]:
b = np.random.randint(10,100,size=(5,4))
b

array([[68, 60, 88, 77],
       [96, 78, 15, 10],
       [51, 89, 97, 47],
       [46, 31, 75, 97],
       [39, 72, 28, 95]], dtype=int32)

In [27]:
c = b[:3,:2]
c

array([[68, 60],
       [96, 78],
       [51, 89]], dtype=int32)

In [29]:
d = a.reshape(4,5)
d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [33]:
e = d.reshape(1,20)
print(e)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]]


In [35]:
f = np.matmul(b,d)
f

array([[2628, 2921, 3214, 3507, 3800],
       [ 889, 1088, 1287, 1486, 1685],
       [2404, 2688, 2972, 3256, 3540],
       [2609, 2858, 3107, 3356, 3605],
       [2299, 2533, 2767, 3001, 3235]])

In [38]:
g = np.random.randint(0,100,size=(1,100))
g

array([[95, 34, 33, 42, 44, 22, 57, 43, 90, 33, 28, 21, 46,  7, 81, 14,
        32, 82, 33, 91, 93,  1,  6, 56, 59, 40, 30, 22, 20, 26, 97,  5,
        19, 53, 79, 60, 85, 52, 10,  2, 55, 32, 25, 11, 32, 22, 77, 15,
        92, 38, 68, 78, 88, 21, 76, 86, 60, 77, 60, 37, 85, 71, 13, 86,
        45, 31, 10, 96, 46, 44, 53, 32, 49, 89, 73, 13, 14, 80, 79,  1,
        46, 55, 13, 15, 92, 62, 10,  0, 18, 99, 79, 53, 16, 95, 65, 54,
        58, 81, 30, 51]], dtype=int32)

In [45]:
h = g>50 #boolean indices
g[h]

array([95, 57, 90, 81, 82, 91, 93, 56, 59, 97, 53, 79, 60, 85, 52, 55, 77,
       92, 68, 78, 88, 76, 86, 60, 77, 60, 85, 71, 86, 96, 53, 89, 73, 80,
       79, 55, 92, 62, 99, 79, 53, 95, 65, 54, 58, 81, 51], dtype=int32)

In [58]:
g[0,[1,2,3,5,8,13,21,34]] #fancy indexing with fibonacci indices, because why not

array([34, 33, 42, 22, 90,  7,  1, 79], dtype=int32)

In [68]:
b #2D array created earlier
mean = b.mean(axis=0)
print(mean)
print(b.max(axis=0))
print(b.sum(axis=0))

[60.  66.  60.6 65.2]
[96 89 97 97]
[300 330 303 326]


In [73]:
mask = b>mean
b[mask]

array([68, 88, 77, 96, 78, 89, 97, 75, 97, 72, 95], dtype=int32)

**Part 3**

- A few python tasks

In [76]:
a = 1
b = 1
fib = []
fib.append(a)
fib.append(b)
for i in range(98):
    c = a+b
    b = c
    a = b
    fib.append(c)
print(fib)

[1, 1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768, 65536, 131072, 262144, 524288, 1048576, 2097152, 4194304, 8388608, 16777216, 33554432, 67108864, 134217728, 268435456, 536870912, 1073741824, 2147483648, 4294967296, 8589934592, 17179869184, 34359738368, 68719476736, 137438953472, 274877906944, 549755813888, 1099511627776, 2199023255552, 4398046511104, 8796093022208, 17592186044416, 35184372088832, 70368744177664, 140737488355328, 281474976710656, 562949953421312, 1125899906842624, 2251799813685248, 4503599627370496, 9007199254740992, 18014398509481984, 36028797018963968, 72057594037927936, 144115188075855872, 288230376151711744, 576460752303423488, 1152921504606846976, 2305843009213693952, 4611686018427387904, 9223372036854775808, 18446744073709551616, 36893488147419103232, 73786976294838206464, 147573952589676412928, 295147905179352825856, 590295810358705651712, 1180591620717411303424, 2361183241434822606848, 4722366482869645213696, 944473296573929042739

In [77]:
for i in range(1,51):
    div3 = i%3==0
    div5=i%5==0
    if(div3 and div5):
        print("FizzBuzz")
    elif(div3):
        print("Fizz")
    elif(div5):
        print("Buzz")

Fizz
Buzz
Fizz
Fizz
Buzz
Fizz
FizzBuzz
Fizz
Buzz
Fizz
Fizz
Buzz
Fizz
FizzBuzz
Fizz
Buzz
Fizz
Fizz
Buzz
Fizz
FizzBuzz
Fizz
Buzz


In [80]:
import statistics
inList = input()
print(statistics.median(inList))

 [2,3,4,5,1,2,4,2]


2


In [81]:
var = 0
print("Keep entering numbers, enter -1 to stop: ")
inpList2 = []
while(True):
    var = int(input())
    if(var==-1):
        break
    inpList2.append(var)
print(statistics.mean(inpList2))

Keep entering numbers, enter -1 to stop: 


 2
 3
 10
 9
 -1


6


In [86]:
try:
    a = float(input("Enter Numerator: "))
    b = float(input("Enter Denominator: "))
    c = a/b
    print("Quotient: ", c)
except ZeroDivisionError:
    print("Oh no, it’s math doom,\nDivide by zero, and soon—\nYour code meets its tomb.")
    

Enter Numerator:  9
Enter Denominator:  0


Oh no, it’s math doom,
Divide by zero, and soon—
Your code meets its tomb.


**Part 4**

- Bonus Challenge

In [88]:
arr3d = np.random.rand(2,2,2)
print(arr3d)

[[[0.06316369 0.16322417]
  [0.62270379 0.64057065]]

 [[0.78689589 0.09924296]
  [0.07817968 0.12244736]]]


In [90]:
swapped = np.swapaxes(arr3d,0,1)
print(swapped)

[[[0.06316369 0.16322417]
  [0.78689589 0.09924296]]

 [[0.62270379 0.64057065]
  [0.07817968 0.12244736]]]


In [92]:
toAdd = np.random.rand(2,2)
print(arr3d+toAdd) #broadcasting

[[[0.102916   0.46602545]
  [1.52913047 0.79924646]]

 [[0.8266482  0.40204424]
  [0.98460637 0.28112317]]]
